# This is a basic workflow to help you get started with Actions

name: 'CI-publish'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [ created ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
#    runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: deploy
        env:
          SIGNING_KEY_ID: ${{ secrets.OSSRH_SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.OSSRH_SIGNING_SECRET_KEY_RING_FILE }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          NEXUS_HOST: ${{ secrets.OSSRH_HOST }}
          NEXUS_USER: ${{ secrets.OSSRH_USER }}
          NEXUS_PASS: ${{ secrets.OSSRH_PASS }}
