name: 'Publish'

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Publish to Maven Central
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publishAndReleaseToMavenCentral
        env:
          SIGNING_KEY_ID: ${{ secrets.OSSRH_SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.OSSRH_SIGNING_SECRET_KEY_RING_FILE }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          NEXUS_USER: ${{ secrets.OSSRH_USER }}
          NEXUS_PASS: ${{ secrets.OSSRH_PASS }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: |
            ${{ secrets.OSSRH_SIGNING_SECRET_KEY_RING_FILE }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.OSSRH_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASS }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}